Task 1
kabernardes/trainee-web-page pull request #1
Opened 2022-02-07 20:31 UTC by kabernardes

Adding some style with ITCSS.

2022-02-07 20:40 UTC, iagodahlem requested changes
Bom começo, deixei alguns comentários.

2022-02-07 20:40 UTC, iagodahlem commented on src/styles/settings/_settings.css
> +  --body-font: 'Montserrat', sans-serif;
👍

2022-02-07 20:40 UTC, iagodahlem commented on src/styles/index.css
> +@import 'settings/_settings.css';
A ordem dos imports tem sempre que respeitar a mesma ordem da pirâmide, então as settings sempre são primeiro.

2022-02-07 20:40 UTC, iagodahlem commented on src/styles/elements/_body.css
> +  font-size: var(--body-font);
Acho que aqui a variável ficou errada.

2022-02-07 20:40 UTC, iagodahlem commented on src/styles/elements/_body.css
> +  font: var(--body-font);
A propriedade `font` não existe, acho que tu quis usar `font-family`.

2022-02-07 20:51 UTC, kabernardes commented on src/styles/elements/_body.css
> +  font: var(--body-font);
Obrigada, corrigi tudo!  As outras propriedades do css vou colocando aos poucos com o avanço das proximas tasks!

2022-02-08 12:49 UTC, iagodahlem approved these changes
Muito bom Kátia! 👏 

Pode dar merge!

2022-02-08 13:56 UTC, merged