Task 2
kabernardes/trainee-web-page pull request #2
Opened 2022-02-07 22:27 UTC by kabernardes

- Adding buttons.
- Adding inputs.

2022-02-09 01:35 UTC, iagodahlem requested changes
Adciona uma screenshot 🙏

2022-02-09 10:24 UTC, kabernardes commented
> Adciona uma screenshot pray

Adicionado!

2022-02-09 20:26 UTC, iagodahlem requested changes
Os estilos dos components não seguiram estritamente o design passado, mas gostei de como ficou. Deixei alguns comentários pra arrumar.

2022-02-09 20:26 UTC, iagodahlem commented on src/design-system.html
> +      <button class ="button button--general">STATIC</button>
💅

```suggestion
<button class="button button--general">STATIC</button>
```

Mesma coisa para as outras linhas.

2022-02-09 20:26 UTC, iagodahlem commented on src/styles/components/_button.css
> +.button{
💅

```suggestion
.button {
```

2022-02-09 20:26 UTC, iagodahlem commented on src/styles/components/_button.css
> +  font-weight: bolder;
Pra `font-weight` é sempre bom usar numeros especificos como `400`, `700`, etc... Usando as palavras como `bolder` as vezes o browser não sabe bem qual peso aplicar e deixa a fonte rasterizada.

2022-02-09 20:26 UTC, iagodahlem commented on src/styles/components/_button.css
> +  cursor: default;
Pra disabled é legal usar o cursor `not-allowed`, fica com uma UX melhor.

2022-02-09 20:26 UTC, iagodahlem commented on src/styles/components/_button.css
> +.button--active, button--general:active{
Acho que aqui deveria ser classe né?
```suggestion
.button--active, .button--general:active{
```

2022-02-09 20:26 UTC, iagodahlem commented on src/styles/index.css
> +@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css");
Sempre bom evitar fazer imports de fonts ou icones no CSS, apesar disso ser aplicavel pra todas as paginas, costuma ser mais lento e trava o carregamento do CSS, já que o browser precisa primeiro fazer download do arquivo de CSS, pra então enxergar esse import e começar a fazer download da fonte tambem.

Adiciona como uma tag link nos htmls tambem. Antes da linha do link do index.css

2022-02-09 20:58 UTC, kabernardes commented on src/styles/index.css
> +@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css");
Obrigada por todas as dicas, arrumei tudo!

2022-02-10 17:54 UTC, iagodahlem approved these changes

2022-02-10 17:54 UTC, iagodahlem commented on src/styles/index.css
> +@import 'components/_input';
Não sabia que dava pra remover a extensão com Parcel, boa!

2022-02-10 17:56 UTC, kabernardes commented on src/styles/index.css
> +@import 'components/_input';
Funcionou, aí deixei sem, achei mais limpo, mas se precisar, coloco de novo!

2022-02-10 17:57 UTC, merged